#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass BPL_CosmeticFunctions.BPL_CosmeticFunctions_C
class UBPL_CosmeticFunctions_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UBPL_CosmeticFunctions_C* GetDefaultObj();

	void Build_Thumbnail_Path(bool BuildFullpath, class UObject* __WorldContext, class FString* Path, const class FString& LOCAL_Path, const class FString& CallFunc_GetProjectContentDirectory_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue);
	void Build_Thumbnail_Filename(const class FString& CosmeticId, class UObject* __WorldContext, class FString* Filename, const class FString& LOCAL_Prefix, const class FString& LOCAL_Path, const class FString& CallFunc_Concat_StrStr_ReturnValue);
	void SaveThumbnails(TMap<class FString, class UTextureRenderTarget2D*> ThumbnailMap, class UObject* __WorldContext, const class FString& CallFunc_Build_Thumbnail_Path_Path, TArray<class FString>& CallFunc_Map_Keys_Keys, const class FString& CallFunc_Concat_StrStr_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const class FString& CallFunc_Array_Get_Item, const class FString& CallFunc_Build_Thumbnail_Filename_Filename, class UTextureRenderTarget2D* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class UTexture2D* CallFunc_SaveRenderTargetAsTexture2DEditorOnly_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void LoadCosmeticThumbnailByID(const class FString& ID, class UObject* __WorldContext, class UTexture2D** Result, bool* Success, const class FString& CallFunc_Build_Thumbnail_Filename_Filename, const class FString& CallFunc_Build_Thumbnail_Path_Path, int32 Temp_int_Array_Index_Variable, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, TScriptInterface<class IAssetRegistry> CallFunc_GetAssetRegistry_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, class FName CallFunc_Conv_StringToName_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable, class FName CallFunc_Conv_StringToName_ReturnValue_1, const struct FAssetData& CallFunc_GetAssetByObjectPath_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UObject* CallFunc_GetAsset_ReturnValue, class UTexture2D* K2Node_DynamicCast_AsTexture_2D, bool K2Node_DynamicCast_bSuccess, TScriptInterface<class IAssetRegistry> CallFunc_GetAssetRegistry_ReturnValue_1, TArray<struct FAssetData>& CallFunc_GetAssetsByPackageName_OutAssetData, bool CallFunc_GetAssetsByPackageName_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FAssetData& CallFunc_Array_Get_Item, class UObject* CallFunc_GetAsset_ReturnValue_1, class UTexture2D* K2Node_DynamicCast_AsTexture_2D_1, bool K2Node_DynamicCast_bSuccess_1);
	void LoadEmoteThumbnails(TArray<class FString>& EmoteIDs, class UObject* __WorldContext, TMap<class UClass*, class UTexture2D*>* EmoteThumbs, TMap<class UClass*, class UTexture2D*> LOCAL_Thumbs, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, const class FString& CallFunc_Array_Get_Item, class UTexture2D* CallFunc_LoadCosmeticThumbnailByID_Result, bool CallFunc_LoadCosmeticThumbnailByID_Success, int32 Temp_int_Loop_Counter_Variable, class UQtnCharacterBodyMesh* CallFunc_Get_Cosmetic_Item_From_Id_OutBodyMesh, TSubclassOf<class UQtnEmoteVerb_Archetype_C> CallFunc_Get_Cosmetic_Item_From_Id_OutEmoteVerb, class UClass* K2Node_ClassDynamicCast_AsQtn_Emote_Verb_Archetype, bool K2Node_ClassDynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void IsCosmeticAnEmote(class UClass* VerbClass, class UObject* __WorldContext, class UClass** EmoteClass, bool* IsEmote, class UClass* K2Node_ClassDynamicCast_AsQtn_Emote_Verb_Archetype, bool K2Node_ClassDynamicCast_bSuccess, bool CallFunc_IsValidClass_ReturnValue);
	void LoadThumbnails(TArray<struct FQtnCosmeticCatalogueEntry>& EntriesToLoad, class UObject* __WorldContext, TMap<class FString, class UTexture2D*>* ResultMap, TMap<class UClass*, class UTexture2D*>* EmotesMap, TMap<class UClass*, class UTexture2D*> LOCAL_EmoteThumbs, TMap<class FString, class UTexture2D*> LOCAL_Thumbs, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FQtnCosmeticCatalogueEntry& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UTexture2D* CallFunc_LoadCosmeticThumbnailByID_Result, bool CallFunc_LoadCosmeticThumbnailByID_Success, class UClass* CallFunc_IsCosmeticAnEmote_EmoteClass, bool CallFunc_IsCosmeticAnEmote_IsEmote, int32 CallFunc_Add_IntInt_ReturnValue, class UTexture2D* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void FetchPlayerCurrencyAmountByTag(class AQtnBodyPawn* TargetPlayer, const struct FGameplayTag& CurrencyTag, class UObject* __WorldContext, int32* OutCurrencyAmount, class UQtnInventoryComponent* CallFunc_GetBodyInventory_ReturnValue, int32 CallFunc_GetCurrencyQuantity_ReturnValue);
	void Can_Player_Afford_Cosmetic_Item(class ABodyPawnPlayer_C* TargetPlayer, struct FQtnCosmeticCatalogueEntry& Item, class UObject* __WorldContext, bool* CanAfford_, int32 Temp_int_Array_Index_Variable, TArray<class FString>& CallFunc_Map_Keys_Keys, const class FString& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_FetchPlayerCurrencyAmount_OutCurrencyAmount, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue);
	void Can_Player_Afford_Item(class ABodyPawnPlayer_C* TargetPlayer, struct FFQtnStoreItem& Item, class UObject* __WorldContext, bool* CanAfford_, int32 Temp_int_Array_Index_Variable, TArray<class FString>& CallFunc_Map_Keys_Keys, const class FString& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_FetchPlayerCurrencyAmount_OutCurrencyAmount, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue);
	void FetchPlayerCurrencyAmount(class ABodyPawnPlayer_C* TargetPlayer, const class FString& CurrencyCode, class UObject* __WorldContext, int32* OutCurrencyAmount, const struct FGameplayTag& CallFunc_GetCurrencyGameplayTag_ReturnValue, bool CallFunc_IsProxyInventoryCurrency_ReturnValue, bool CallFunc_IsUserAccountCurrency_ReturnValue, class UQtnInventoryComponent* CallFunc_GetBodyInventory_ReturnValue, int32 CallFunc_GetCurrencyQuantity_ReturnValue);
	void Format_Cosmetic_Price_Label(TArray<struct FFQtnCurrencyCodeValuePair>& CurrencyCodes, class ABodyPawnPlayer_C* PlayerBodyPawn, class UObject* __WorldContext, class FText* Text, class FText PriceText, class FText Temp_text_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FFQtnCurrencyCodeValuePair& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, float CallFunc_Conv_IntToFloat_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, float CallFunc_Divide_FloatFloat_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, int32 CallFunc_FetchPlayerCurrencyAmount_OutCurrencyAmount, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, bool CallFunc_LessEqual_IntInt_ReturnValue_1, class FText CallFunc_Format_ReturnValue, bool CallFunc_NotEqual_StrStr_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class FText Temp_text_Variable_1, bool Temp_bool_Variable, class FText K2Node_Select_Default, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, class FText CallFunc_TextToUpper_ReturnValue, class FText CallFunc_Format_ReturnValue_1);
	void Get_All_NonMinusZero_Currency_Codes(TMap<class FString, int32>& Price_Map, class UObject* __WorldContext, TArray<struct FFQtnCurrencyCodeValuePair>* OutPriceCodes, const TArray<struct FFQtnCurrencyCodeValuePair>& CodeValuePairsArray, TArray<int32>& CallFunc_Map_Values_Values, TArray<class FString>& CallFunc_Map_Keys_Keys, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_Array_Get_Item, const struct FFQtnCurrencyCodeValuePair& K2Node_MakeStruct_FQtnCurrencyCodeValuePair, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Get_Cosmetic_Item_From_Id(class UObject* WorldReference, const class FString& ItemId, bool IsEmote, class UObject* __WorldContext, class UQtnCharacterBodyMesh** OutBodyMesh, TSubclassOf<class UQtnEmoteVerb_Archetype_C>* OutEmoteVerb, class FName CallFunc_Conv_StringToName_ReturnValue, const struct FQtnCosmeticCatalogueEntry& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, class UClass* CallFunc_LoadClassAsset_Blocking_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsQtn_Emote_Verb_Archetype, bool K2Node_ClassDynamicCast_bSuccess, class UClass* K2Node_ClassDynamicCast_AsQtn_Character_Body_Mesh, bool K2Node_ClassDynamicCast_bSuccess_1, class UQtnCharacterBodyMesh* CallFunc_GetClassDefaultObject_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, TSubclassOf<class UObject> CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsQtn_Character_Body_Mesh_1, bool K2Node_ClassDynamicCast_bSuccess_2, bool CallFunc_IsValidClass_ReturnValue_1, class UClass* K2Node_ClassDynamicCast_AsQtn_Character_Body_Mesh_2, bool K2Node_ClassDynamicCast_bSuccess_3, class UQtnCharacterBodyMesh* CallFunc_GetClassDefaultObject_ReturnValue_1);
	void Check_Item_for_Player_Ownership(class ABodyPawnPlayer_C* Player, class UBodyDataBag_C* BodyDataBag, const class FString& ItemId, class UObject* __WorldContext, bool* HasOwnership, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, class UQtnCharacterAppearanceComponent* CallFunc_GetBodyAppearanceComponent_ReturnValue, TArray<class FString>& CallFunc_GetVaultEmotesData_ReturnValue, TArray<class FString>& CallFunc_GetVaultCosmeticsData_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_2, bool CallFunc_Array_Contains_ReturnValue_3);
};

}


