#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x59 (0x151 - 0xF8)
// BlueprintGeneratedClass SpokeBP.SpokeBP_C
class USpokeBP_C : public UQtnSpokeComponent
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xF8(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                        MaxBullshits;                                      // 0x100(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2AC3[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UEnemyBSManagerComponent_C*            CachedEnemyBSManager;                              // 0x108(0x8)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class USkirmishActionBSWindowOpen_C*> OpenBSWindows;                                     // 0x110(0x10)(Edit, BlueprintVisible, Transient, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class USkirmishActionBSWindowOpen_C*> RemainingPotentialBSWindows;                       // 0x120(0x10)(Edit, BlueprintVisible, Transient, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UClass*>                        ValidEnemyBS;                                      // 0x130(0x10)(Edit, BlueprintVisible, Transient, DisableEditOnInstance)
	TArray<class USkirmishActionBSWindowOpen_C*> ChosenBSWindows;                                   // 0x140(0x10)(Edit, BlueprintVisible, Transient, DisableEditOnInstance, ContainsInstancedReference)
	bool                                         HasBeenVisited;                                    // 0x150(0x1)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)

	static class UClass* StaticClass();
	static class USpokeBP_C* GetDefaultObj();

	class FString BuildTextForLabel(const class FString& CallFunc_BuildTextForLabel_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1);
	void AddChosenFromPotentialsUnchecked(class UClass* ChosenBSType, bool* Success, int32 ChosenIndex, int32 NumPotentials, class UClass* LocalChosenBS, int32 LocalStartingIndex, class USkirmishActionBSWindowOpen_C* ChosenPotential, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, class USkirmishActionBSWindowOpen_C* CallFunc_Array_Get_Item, int32 CallFunc_RandomIntegerInRange_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void AddChosenFromPotentialsSafely(class UClass* ChosenBSType, bool* Success, bool CallFunc_AddChosenFromPotentialsUnchecked_success, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void DisplayDebugForBSWindow(class USkirmishActionBSWindowOpen_C* bsWindow, class UQtnDebugWrapper* DebugWrapper, bool IsChosen, class USkirmishActionBSWindowOpen_C* LocalBSWindow, const class FString& Label, class UQtnDebugWrapper* LocalDebugWrapper, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_GetClassNameWithoutSuffix_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class UClass* CallFunc_Array_Get_Item, bool CallFunc_IsValidBS_ReturnValue, const class FString& CallFunc_GetClassNameWithoutSuffix_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class UObject* CallFunc_GetOuterObject_ReturnValue, const class FString& CallFunc_GetDisplayName_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, bool CallFunc_Array_Contains_ReturnValue, const class FString& CallFunc_SelectString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, const class FString& CallFunc_Concat_StrStr_ReturnValue_5);
	void OnDebugDisplay(class UQtnDebugWrapper* DebugWrapper, const struct FColor& VisitColor, class UQtnDebugWrapper* LocalDebugWrapper, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, const class FString& CallFunc_SelectString_ReturnValue, const struct FColor& CallFunc_MakeRandomColor_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_1, class USkirmishActionBSWindowOpen_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_2, const class FString& CallFunc_Conv_IntToString_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_2);
	void CloseSkirmishBSWindow_ServerOnly(class USkirmishActionBSWindowOpen_C* bsWindow, int32 Temp_int_Array_Index_Variable, class UClass* CallFunc_Array_Get_Item, class UClass* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, enum class EQtnOutputYesNoEnum CallFunc_IsThisMapForHordeMode_outputPin, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_Array_Contains_ReturnValue);
	void OpenSkirmishBSWindow_ServerOnly(class USkirmishActionBSWindowOpen_C* bsWindow, class USkirmishActionBSWindowOpen_C* LocalBSWindow, class ASkirmishBase_C* FromSkirmish, class UObject* CallFunc_GetOuterObject_ReturnValue, class ASkirmishBase_C* K2Node_DynamicCast_AsSkirmish_Base, bool K2Node_DynamicCast_bSuccess);
	void DoesBSWindowContainValidBS(class USkirmishActionBSWindowOpen_C* bsWindow, bool* Result, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, class UClass* CallFunc_Array_Get_Item, bool CallFunc_IsValidBS_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	bool IsValidBS(class UClass*& BSType, bool CallFunc_Array_Contains_ReturnValue);
	void SetupChosenBS_ServerOnly(TArray<class UClass*>& ScheduledBS, int32 StartingIndex, int32* NextIndex, int32 LastIndex, int32 LocalScheduledBSCount, int32 LocalStartingIndex, const TArray<class UClass*>& LocalScheduledBS, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, class UClass* CallFunc_Array_Get_Item, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Percent_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, class UClass* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_AddChosenFromPotentialsUnchecked_success, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_3, int32 Temp_int_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_5, bool CallFunc_LessEqual_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1, TSoftObjectPtr<class AQtnSkirmish> CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_4, class UObject* CallFunc_LoadAsset_Blocking_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, class ASkirmishBase_C* K2Node_DynamicCast_AsSkirmish_Base, bool K2Node_DynamicCast_bSuccess, TArray<class UQtnSkirmishAction*>& CallFunc_GatherSkirmishActions_gatheredActions, bool CallFunc_isValidToday_valid_today, class UQtnSkirmishAction* CallFunc_Array_Get_Item_3, class USkirmishActionBSWindowOpen_C* K2Node_DynamicCast_AsSkirmish_Action_BSWindow_Open, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_Length_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_2, bool CallFunc_DoesBSWindowContainValidBS_result);
	void IsChosenBS(class USkirmishActionBSWindowOpen_C* bsWindowOpen, bool* IsChosen, bool CallFunc_Array_Contains_ReturnValue);
	void Close_All_BSWindows_Server_Only();
	void HandleBSTrigger_ServerOnly(class UClass* EnemyBS, const TArray<class UClass*>& ChosenBSToReplace, int32 NumChosensToReplace, class UObject* ClosingBSOuter, class UClass* TriggeredBS, class USkirmishActionBSWindowOpen_C* ClosingBSWindow, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, int32 Temp_int_Loop_Counter_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_2, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable_3, bool CallFunc_Not_PreBool_ReturnValue, enum class EQtnOutputYesNoEnum CallFunc_IsThisMapForHordeMode_outputPin, int32 Temp_int_Loop_Counter_Variable_4, bool K2Node_SwitchEnum_CmpSuccess, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_4, enum class EQtnOutputYesNoEnum CallFunc_IsThisMapForHordeMode_outputPin_1, class USkirmishActionBSWindowOpen_C* CallFunc_Array_Get_Item, bool K2Node_SwitchEnum_CmpSuccess_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable_1, class UClass* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_AddChosenFromPotentialsSafely_success, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, class UObject* CallFunc_GetOuterObject_ReturnValue, class USkirmishActionBSWindowOpen_C* CallFunc_Array_Get_Item_2, class USkirmishActionBSWindowOpen_C* CallFunc_Array_Get_Item_3, class UObject* CallFunc_GetOuterObject_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, class UObject* CallFunc_GetOuterObject_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Max_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Max_ReturnValue_1, bool CallFunc_Array_RemoveItem_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_4, class USkirmishActionBSWindowOpen_C* CallFunc_Array_Get_Item_4, bool CallFunc_Less_IntInt_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue_2);
	void Handle_BSWindow_Close_Server_Only(class USkirmishActionBSWindowOpen_C* bsWindow, bool CallFunc_Array_RemoveItem_ReturnValue, bool CallFunc_AddChosenFromPotentialsSafely_success, bool CallFunc_Array_RemoveItem_ReturnValue_1);
	void Handle_BSWindow_Open_ServerOnly(class USkirmishActionBSWindowOpen_C* bsWindow, class USkirmishActionBSWindowOpen_C* LocalBSWindow, bool CallFunc_IsChosenBS_isChosen, enum class EQtnOutputYesNoEnum CallFunc_IsThisMapForHordeMode_outputPin, class UClass* CallFunc_Array_Get_Item, bool K2Node_SwitchEnum_CmpSuccess, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue);
	void ReceiveBeginPlay();
	void BullshitApplied_ServerOnly_Event_0(class UClass* Bullshit);
	void ExecuteUbergraph_SpokeBP(int32 EntryPoint, class UClass* K2Node_CustomEvent_Bullshit, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class AQtnGameState* CallFunc_GetQtnGameState_ReturnValue, class AQtnGameStateArchetype_C* K2Node_DynamicCast_AsQtn_Game_State_Archetype, bool K2Node_DynamicCast_bSuccess, bool CallFunc_HasAuthority_ReturnValue);
};

}


